### ISSUE TITLE
Not able to open rugged-box-gridfinity.scad

### ISSUE THREAD

**Issue by 3DEngelen** [smkent/monoscad#357]
I cloned the full repo, and tried to open rugged-box-gridfinity.scad, but it fails to open on my system.
There are no issues for me for opening rugged-box.scad so i guess my openscad is setup correctly.

Can you chech this?

thx

**Comment by smkent** [comment]
Hi! Have you cloned the repository submodules? In the repository root, run `git submodule update --init --recursive`. If you're still experiencing errors afterwards, please share what you're seeing and I will take a look.

**Comment by smkent** [comment]
Hi, it's been over a month so I'm going to close this issue. If you are still experiencing problems feel free to reopen it and let me know!
