### ISSUE TITLE
Draw latch handle is too long

### ISSUE THREAD

**Issue by muntyan** [smkent/monoscad#366]
If the box isn't high enough, then the latch handle extends down past the bottom of the box, so when you put it down, the latch opens automatically. See attached pictures. Here bottom height is 4, and top height is 1.

![20240602_124844](https://github.com/smkent/monoscad/assets/17531749/89dbf24b-8934-4014-90fc-650400628752)
![20240602_124904](https://github.com/smkent/monoscad/assets/17531749/157ae44d-f018-4d32-8633-5fc3469ac8d5)

Thanks for sharing, great stuff!

**Comment by smkent** [comment]
@muntyan Hi! I hope you like the box!

The draw latch handle is a fixed size, so unfortunately it is taller than boxes below a certain height. This is documented in the model's README (which is the same as the [model's description on Printables](https://www.printables.com/model/757297)):

https://github.com/smkent/monoscad/blob/64da2ee162377b529f0e6e84f08939e069e9cdc9/gridfinity/rugged-box/README.md?plain=1#L132-L133

As alternatives, you could:

* Use clip latches (the other latch option included in the model)
* Try one of the two [shorter](https://www.printables.com/model/786709-shorter-draw-latch-for-6u-gridfinity-rugged-boxes) draw [latch](https://www.printables.com/model/771420-compact-double-action-latch-for-4x4x6-boxes) remixes made by other folks

**Comment by muntyan** [comment]
My bad, didn't RTFM. Yeah, clips should be just fine. And I do love the box :)
